"use client";
import { useEffect, useMemo, useState } from "react";
type Staff={id:string;name:string;email:string};type Slot={id:number;coach_id:string;coach_name:string;venue:string;court:string;start_at:string;end_at:string;price_pence:number;status:string;court_confirmed_until:string};type Connection={coach_id:string;google_email:string;connected_at:string};
const money=(p:number)=>`£${(p/100).toFixed(2)}`;const dt=(v:string)=>new Date(v).toLocaleString("en-GB",{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"});
const card={background:"#fff",border:"1px solid #dfe6e1",borderRadius:14,padding:20,boxShadow:"0 4px 20px rgba(0,0,0,.04)"} as const;
const field={width:"100%",padding:"11px 12px",border:"1px solid #cfd8d2",borderRadius:9,fontSize:15,boxSizing:"border-box"} as const;
export default function PrivateLessonsClient(){
 const [staff,setStaff]=useState<Staff[]>([]),[slots,setSlots]=useState<Slot[]>([]),[connections,setConnections]=useState<Connection[]>([]),[message,setMessage]=useState(""),[working,setWorking]=useState(false);
 const [form,setForm]=useState({coachId:"",venue:"Warsash",court:"",date:"",time:"",duration:"60",price:"50",notes:""});
 const load=async()=>{const r=await fetch("/api/private-lessons/manage",{cache:"no-store"});const x=await r.json();if(!r.ok){setMessage(x.error||"Could not load private lessons");return}setStaff(x.staff||[]);setSlots(x.slots||[]);setConnections(x.connections||[]);setForm(f=>({...f,coachId:f.coachId||x.staff?.[0]?.id||""}))};
 useEffect(()=>{void load()},[]);useEffect(()=>{const p=new URLSearchParams(window.location.search);if(p.get("calendar")==="connected")setMessage("Google Calendar connected for this coach.");if(p.get("calendar")==="error")setMessage(p.get("message")||"Google Calendar connection failed.")},[]);
 const connected=new Map(connections.map(c=>[c.coach_id,c]));
 const create=async()=>{if(working)return;const start=new Date(`${form.date}T${form.time}:00`),end=new Date(start.getTime()+Number(form.duration)*60000);if(!form.date||!form.time||Number.isNaN(start.getTime())){setMessage("Choose a date and time.");return}setWorking(true);setMessage("");const r=await fetch("/api/private-lessons/manage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"createSlot",coachId:form.coachId,venue:form.venue,court:form.court,startAt:start.toISOString(),endAt:end.toISOString(),pricePence:Math.round(Number(form.price||0)*100),notes:form.notes})});const x=await r.json();setWorking(false);if(!r.ok){setMessage(x.error||"Slot could not be created");return}setMessage("Bookable slot created. Court confirmation is valid for 24 hours.");setForm(f=>({...f,court:"",date:"",time:"",notes:""}));await load()};
 const act=async(action:string,id:number)=>{const r=await fetch("/api/private-lessons/manage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,id})});const x=await r.json();setMessage(r.ok?(action==="reconfirmCourt"?"Court rechecked. Slot is live for another 24 hours.":"Slot cancelled."):(x.error||"Action failed"));if(r.ok)await load()};
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"34px 22px",fontFamily:"Arial,sans-serif",color:"#17211b"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",flexWrap:"wrap"}}><div><a href="/" style={{color:"#183d2f",fontWeight:700,textDecoration:"none"}}>← Supreme Tennis Admin</a><p style={{margin:"20px 0 4px",fontSize:12,textTransform:"uppercase",letterSpacing:1,fontWeight:800}}>Private coaching</p><h1 style={{margin:"0 0 8px",fontSize:34}}>Private Lesson Diary</h1><p style={{maxWidth:720,margin:0,color:"#59645e"}}>Stage 1: a coach checks ClubSpark or ClubSync first, then opens only genuinely available court slots for clients.</p></div><a href="/book-private" target="_blank" style={{padding:"11px 15px",borderRadius:9,background:"#183d2f",color:"#fff",fontWeight:700,textDecoration:"none"}}>Open client booking page</a></div>
  {message&&<div style={{...card,marginTop:18,background:"#f2f8f4"}}>{message}</div>}
  <section style={{...card,marginTop:20}}><h2 style={{marginTop:0}}>1. Coach Google Calendars</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:16}}>{staff.map(coach=>{const c=connected.get(coach.id);return <div key={coach.id} style={{border:"1px solid #e1e7e3",borderRadius:11,padding:14}}><strong>{coach.name}</strong><div style={{margin:"8px 0 12px",color:"#637069",fontSize:14}}>{c?`Connected: ${c.google_email}`:"Not connected"}</div><a href={`/api/calendar/connect?coachId=${encodeURIComponent(coach.id)}`} style={{padding:"9px 12px",border:"1px solid #b7c4bd",borderRadius:8,background:"#fff",fontWeight:700,textDecoration:"none",color:"#17211b"}}>{c?"Reconnect Google Calendar":"Connect Google Calendar"}</a></div>})}</div></section>
  <section style={{...card,marginTop:20}}><h2 style={{marginTop:0}}>2. Open a client-bookable lesson</h2><p style={{color:"#5c6861"}}><strong>Important:</strong> check the venue court system immediately before creating the slot. Warsash = ClubSpark. Abshot = ClubSync.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}>
   <label>Coach<select style={field} value={form.coachId} onChange={e=>setForm({...form,coachId:e.target.value})}>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
   <label>Venue<select style={field} value={form.venue} onChange={e=>setForm({...form,venue:e.target.value})}><option>Warsash</option><option>Abshot</option></select></label>
   <label>Court<input style={field} placeholder="e.g. Court 2" value={form.court} onChange={e=>setForm({...form,court:e.target.value})}/></label>
   <label>Date<input style={field} type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label>
   <label>Start time<input style={field} type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label>
   <label>Length<select style={field} value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="90">90 minutes</option></select></label>
   <label>Price (£)<input style={field} type="number" min="0" step="0.5" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label>
   <label>Internal note<input style={field} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
  </div><button style={{marginTop:16,padding:"11px 15px",border:0,borderRadius:9,background:"#183d2f",color:"#fff",fontWeight:700,cursor:"pointer"}} disabled={working} onClick={()=>void create()}>{working?"Creating…":"Court checked - open this slot"}</button><p style={{fontSize:13,color:"#68756e"}}>A manually checked slot automatically expires from the public booking page after 24 hours unless the coach rechecks the court.</p></section>
  <section style={{...card,marginTop:20}}><h2 style={{marginTop:0}}>3. Current private-lesson slots</h2>{!slots.length&&<p>No private-lesson slots yet.</p>}<div style={{display:"grid",gap:10}}>{slots.map(slot=>{const expired=slot.status==="Available"&&new Date(slot.court_confirmed_until)<=new Date();return <div key={slot.id} style={{display:"grid",gridTemplateColumns:"minmax(210px,1.4fr) minmax(180px,1fr) auto",gap:12,alignItems:"center",border:"1px solid #e1e7e3",borderRadius:10,padding:13}}><div><strong>{slot.coach_name}</strong><div>{dt(slot.start_at)} · {slot.venue}{slot.court?` · ${slot.court}`:""}</div><small>{money(slot.price_pence)}</small></div><div><span style={{display:"inline-block",padding:"5px 8px",borderRadius:20,background:"#eaf3ed",fontSize:12,fontWeight:700}}>{slot.status}</span>{expired&&<div style={{fontSize:12,color:"#9b5b00",marginTop:6}}>Court check expired - hidden from clients</div>}</div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{slot.status==="Available"&&<button onClick={()=>void act("reconfirmCourt",slot.id)}>Court rechecked</button>}{slot.status==="Available"&&<button onClick={()=>void act("cancelSlot",slot.id)}>Cancel</button>}</div></div>})}</div></section>
 </main>
}
