"use client";
import { useEffect, useState } from "react";
type Slot={id:number;coach_id:string;coach_name:string;venue:string;court:string;start_at:string;end_at:string;price_pence:number};
const money=(p:number)=>`£${(p/100).toFixed(2)}`;const dt=(v:string)=>new Date(v).toLocaleString("en-GB",{weekday:"long",day:"numeric",month:"long",hour:"2-digit",minute:"2-digit"});const box={background:"#fff",border:"1px solid #dfe6e1",borderRadius:14,padding:20,boxShadow:"0 4px 18px rgba(0,0,0,.05)"} as const;const input={width:"100%",padding:"12px",border:"1px solid #cfd8d2",borderRadius:9,fontSize:16,boxSizing:"border-box"} as const;
export default function BookingClient(){
 const [slots,setSlots]=useState<Slot[]>([]),[chosen,setChosen]=useState<Slot|null>(null),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(""),[confirmed,setConfirmed]=useState<any>(null),[form,setForm]=useState({playerName:"",parentName:"",email:"",phone:"",notes:""});
 const load=async()=>{setLoading(true);const r=await fetch("/api/private-lessons/public",{cache:"no-store"});const x=await r.json();setLoading(false);if(!r.ok){setError(x.error||"Available lessons could not load");return}setSlots(x.slots||[])};useEffect(()=>{void load()},[]);
 const book=async()=>{if(!chosen||working)return;setWorking(true);setError("");const r=await fetch("/api/private-lessons/public",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,slotId:chosen.id})});const x=await r.json();setWorking(false);if(!r.ok){setError(x.error||"Booking failed");await load();return}setConfirmed(x)};
 if(confirmed)return <main style={{maxWidth:720,margin:"0 auto",padding:"50px 20px",fontFamily:"Arial,sans-serif",color:"#17211b"}}><section style={{...box,textAlign:"center",padding:34}}><div style={{fontSize:46}}>✓</div><h1>Private lesson booked</h1><p><strong>{confirmed.slot.coachName}</strong><br/>{dt(confirmed.slot.startAt)}<br/>{confirmed.slot.venue}{confirmed.slot.court?` · ${confirmed.slot.court}`:""}</p><p style={{color:"#5d6962"}}>{confirmed.calendarAdded?"The lesson has also been added to the coach's Google Calendar.":"The booking is confirmed in Supreme Tennis. The coach calendar is not connected yet, so the lesson remains in the Supreme Tennis diary."}</p></section></main>;
 return <main style={{maxWidth:960,margin:"0 auto",padding:"34px 20px",fontFamily:"Arial,sans-serif",color:"#17211b"}}><p style={{fontSize:12,textTransform:"uppercase",letterSpacing:1,fontWeight:800}}>Supreme Tennis</p><h1 style={{fontSize:38,margin:"4px 0 8px"}}>Book a Private Lesson</h1><p style={{color:"#5d6962",maxWidth:700}}>These times have been opened by a coach only after checking court availability. Slots disappear automatically if the court check becomes stale.</p>{error&&<div style={{...box,background:"#fff5f2",margin:"18px 0"}}>{error}</div>}<section style={{...box,marginTop:20}}><h2 style={{marginTop:0}}>Choose a lesson</h2>{loading?<p>Loading available lessons…</p>:!slots.length?<p>No court-confirmed private lessons are available right now. Please check back later or contact Supreme Tennis.</p>:<div style={{display:"grid",gap:10}}>{slots.map(slot=><button key={slot.id} onClick={()=>setChosen(slot)} style={{textAlign:"left",padding:15,borderRadius:10,cursor:"pointer",border:chosen?.id===slot.id?"2px solid #183d2f":"1px solid #dfe6e1",background:chosen?.id===slot.id?"#f0f7f3":"#fff",color:"#17211b"}}><strong>{slot.coach_name}</strong><div>{dt(slot.start_at)}</div><small>{slot.venue}{slot.court?` · ${slot.court}`:""} · {money(slot.price_pence)}</small></button>)}</div>}</section>{chosen&&<section style={{...box,marginTop:20}}><h2 style={{marginTop:0}}>Your details</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:14}}><label>Player name<input style={input} value={form.playerName} onChange={e=>setForm({...form,playerName:e.target.value})}/></label><label>Parent/client name<input style={input} value={form.parentName} onChange={e=>setForm({...form,parentName:e.target.value})}/></label><label>Email<input style={input} type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input style={input} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div><label style={{display:"block",marginTop:14}}>Anything the coach should know?<textarea style={{...input,minHeight:90}} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button onClick={()=>void book()} disabled={working} style={{marginTop:16,padding:"13px 18px",border:0,borderRadius:9,background:"#183d2f",color:"#fff",fontWeight:800,fontSize:16,cursor:"pointer"}}>{working?"Booking…":"Confirm private lesson"}</button></section>}</main>
}
